### ISSUE TITLE
Your module is missing a contact link

### ISSUE THREAD

**Issue by ZenImagine** [jez500/Private-Message-Messenger#10]
![capture du 2018-02-27 12-31-02](https://user-images.githubusercontent.com/29839861/36726450-1cb012de-1bba-11e8-80cf-b2d8ec5e8ec7.png)
On the nodes and the user account, there is a contact link "Private message thread link". But he uses the path /private_messages/id
Your module is missing a contact link.

The link could open for example a modal window ;-)

If you add the contact link, consider posting them for anonymous users with a redirection to login.

**Comment by ZenImagine** [comment]
The` /messenger#new` link is used to create a new conversation. Which link to use to create a new conversation with the author of a node ?

**Comment by jez500** [comment]
`/messenger#new-USERID`
