### ISSUE TITLE
dblog is full of messages "Access denied"

### ISSUE THREAD

**Issue by ZenImagine** [jez500/Private-Message-Messenger#16]
![capture du 2018-02-27 22-55-24](https://user-images.githubusercontent.com/29839861/36757728-9e3c4572-1c12-11e8-96a4-02c28773a3db.png)

![capture du 2018-02-27 15-01-47](https://user-images.githubusercontent.com/29839861/36732931-6c0b84ca-1bcf-11e8-9a76-549e8945c69a.png)
![capture du 2018-02-27 22-55-46](https://user-images.githubusercontent.com/29839861/36757710-96f4ad04-1c12-11e8-8caf-7ec600b5ca3a.png)

**Comment by jez500** [comment]
This should be fixed now :)
