### ISSUE TITLE
The module does not work for anonymous users

### ISSUE THREAD

**Issue by ZenImagine** [jez500/Private-Message-Messenger#17]
I gave permission to anonymous users to use "Private Message".

When I go on the path` /messenger` the anonymous user is redirected to the login page.

Can you make this page visible to anonymous users, if they are allowed to use "Private Message"?

It would be really great if other permission was added:

- Create a private message.
- View private message.

The anonymous user can simply view private messages. It would be useful if the administrator could send a message to all the users (for example an event, a promotion, an update, a welcome message, ...).

**Comment by jez500** [comment]
This is very complex and unlikely it will be done as part of this module, it would have to be first supported by https://www.drupal.org/project/private_message fully
