### ISSUE TITLE
Open first conversation in list after opening /messenger page

### ISSUE THREAD

**Issue by Pls** [jez500/Private-Message-Messenger#18]
Thanks for your work on this module, it really is awesome! Let's make it more awesome.

I found that it would be nice that after opening /messenger page, if there is any conversation in threads it should open first one in list. This is same behavior as FB messenger does and user will expect does.  Currently /messenger page opens and displays only blank page, and user has to click on thread to see conversation.

Can this be achieved by plain JS? I mean reacting after messenger div is displayed, trigger first thread click? Cheers! ;)

**Comment by ZenImagine** [comment]
Maybe this page can be used for other things. For example :

- display recent events of the site (or an advertisement).
- display messaging tips.
- display the statistics of the messages.
- display a list with photos of all users of the site.

**Comment by Pls** [comment]
@ZenImagine, I don't exactly understand your point. You say that /messenger page can be used not only for private messaging?

**Comment by ZenImagine** [comment]
@Pls  I say that when no message is open, we could use the white space to the right of the conversation block to display something useful to the user.

**Comment by jez500** [comment]
As mentioned on #19 you can set your own content on `/messenger` via 
```
function mytheme_preprocess_pmm_thread(&$vars) {
  $vars['welcome_text']['#markup'] = t('Welcome to messenger')
}
```

OR

there is now a tickbox on `/admin/config/private_message/messenger` that will force navigate to the first thread (if it exists) when visiting `/messenger`
