### ISSUE TITLE
Redraw the "New Message" page

### ISSUE THREAD

**Issue by ZenImagine** [jez500/Private-Message-Messenger#19]
It would be great if the "New Message" page was drawn.

It should display the list of all users with the photo 50x50 and below the pseudo (4 columns on desktop and 2 on mobile).

The field that currently allows to select a user could be replaced by a search engine (no, rather a filter) profiles.

Clicking on a user will create a new discussion.

**Comment by jez500** [comment]
This imposes too much, not everyone would want this. I have added ability to set the content of the "welcome" page eg `/messages` via something like:
```
function mytheme_preprocess_pmm_thread(&$vars) {
  $vars['welcome_text']['#markup'] = t('Welcome to messenger')
}
```
So you could technically implement your own logic here
