### ISSUE TITLE
The module does not work for me

### ISSUE THREAD

**Issue by ZenImagine** [jez500/Private-Message-Messenger#2]
I am with Drupal 8.4 and I followed your instructions but the module does not work for me

![capture du 2018-02-23 20-38-03](https://user-images.githubusercontent.com/29839861/36623600-65793218-1906-11e8-9211-0fc5fe79f16a.png)
![capture du 2018-02-23 20-38-18](https://user-images.githubusercontent.com/29839861/36623602-69afa6b4-1906-11e8-91a6-5b0a47c83e02.png)

**Comment by ZenImagine** [comment]
I found the problem.

In /admin/config/development/performance if I check the "Aggregate CSS Files" and "Aggregate JavaScript files" checkboxes, my console is crashing error :

![capture du 2018-02-26 15-13-57](https://user-images.githubusercontent.com/29839861/36674876-b600baa0-1b07-11e8-8148-d2e65b99c92f.png)

If the checkboxes are not checked, it works.

**Comment by jez500** [comment]
Thanks for the bug post, I'll investigate on a vanilla drupal install with aggregation on to see if I can find the cause, sounds like its the order the libraries are loaded?

**Comment by ZenImagine** [comment]
I tested with the Bartik theme but it does not work.

**Comment by jez500** [comment]
I just tested this on new site with aggregation on and couldn't replicate so I think it is fixed, reopen if anyone notices this
