### ISSUE TITLE
Integrate "timeago" into the module

### ISSUE THREAD

**Issue by ZenImagine** [jez500/Private-Message-Messenger#20]
In the next version, can you integrate "timeago" to the module?

With additional parameters in :

`/admin/config/private_message/config`

1) Leave the choice to the administrator to use the date or elapsed time.

2) Add a selection list for the language.

https://github.com/hustcc/timeago.js/tree/master/locales

**Comment by jez500** [comment]
This is done now you can just tick a box and remove other code that includes timeago `/admin/config/private_message/messenger` it will include `timeago.js` from a CDN

With the locals, this is adding too much complexity to the module, you can still do this in your own theme/js with something like

```
if (typeof timeago === 'function') {
var locale = function(number, index, total_sec) {
  return [
    ['just now', 'right now'],
    ['%s seconds ago', 'in %s seconds'],
   ...
  ][index];
};
timeago.register('pt_BR', locale);
}
```
as per https://timeago.org/
