### ISSUE TITLE
Add the active class to li

### ISSUE THREAD

**Issue by ZenImagine** [jez500/Private-Message-Messenger#23]
![capture du 2018-03-23 10-42-15](https://user-images.githubusercontent.com/29839861/37822491-e9bf0a94-2e86-11e8-8f90-5de8a1ba5b19.png)

I want to change the color of the active conversation, but no active class is added to li.

**Comment by Pls** [comment]
```
  /**
   * Messenger Page customizations.
   */
  Drupal.behaviors.visivedejaiMessengerPage = {
    attach: function (context, settings) {
      var url_hash = window.location.hash;
      url_hash = url_hash.replace('#', '');

      $('.pmm-messenger .pmm-thread-teaser').once('visivedejaiMessengerPageOpen').each(function() {
        if ($(this).attr('rel') == url_hash) {
          $(this).addClass('active');
        }
      });

      $('.pmm-messenger .pmm-thread-teaser').click(function() {
        var teaser_rel = $(this).attr('rel');

        $('.pmm-messenger .pmm-thread-teaser').removeClass('active');
        $(this).addClass('active');
      });

      $('.pmm-messenger .pmm-thread__message-text textarea').once('visivedejaiMessengerEnterKeyPress').keypress(function (e) {
        if (e.which == 13 && !e.shiftKey) {
          $('.pmm-thread .pmm-thread__send').trigger('click');
          e.preventDefault();
        }
    });
    }
  };
```
Put this code in your theme JS file and it works as an customization. It currently doesn't work perfectly, tough. I just found that after click on "Recent Messenger Messages" block at the top, this code doesn't currently add "active" class to current conversation. But it works great when navigating threads on /messenger page.

Also, this JS code has an override that after pressing Enter key the message instantly sends, no need to make an extra click. This is the same as Facebook Messenger does submitting messages. Also Shift+Enter can be used for new lines if needed. Feel free to use my code.

You can check it out how I changed the look for my messenger page. Love the work from this module creator and all collaborators. We need something like this polished to have in Drupal!

![zinutes___visivedejai_lt](https://user-images.githubusercontent.com/45207/37868399-550721ec-2fae-11e8-97ec-98842be395e5.png)

**Comment by ZenImagine** [comment]
Thank you. The complete file should look like this ?

```
(function ($) {

  /**
   * Messenger Page customizations.
   */
  Drupal.behaviors.visivedejaiMessengerPage = {
    attach: function (context, settings) {
      var url_hash = window.location.hash;
      url_hash = url_hash.replace('#', '');

      $('.pmm-messenger .pmm-thread-teaser').once('visivedejaiMessengerPageOpen').each(function() {
        if ($(this).attr('rel') == url_hash) {
          $(this).addClass('active');
        }
      });

      $('.pmm-messenger .pmm-thread-teaser').click(function() {
        var teaser_rel = $(this).attr('rel');

        $('.pmm-messenger .pmm-thread-teaser').removeClass('active');
        $(this).addClass('active');
      });

      $('.pmm-messenger .pmm-thread__message-text textarea').once('visivedejaiMessengerEnterKeyPress').keypress(function (e) {
        if (e.which == 13 && !e.shiftKey) {
          $('.pmm-thread .pmm-thread__send').trigger('click');
          e.preventDefault();
        }
    });
    }
  };

})(window.jQuery);
```

The "Enter" key to send the message is a good idea.

It is also necessary that when I click on a conversation, the cursor is automatically put in the text box.

The behavior would be, I click on the conversation and I write my message directly.

Currently I click on the conversation and I have to click on the text box to write a message.

**Comment by Pls** [comment]
> Thank you. The complete file should look like this ?
Yes, thats complete code, you are correct.

> It is also necessary that when I click on a conversation, the cursor is automatically put in the text box.
>The behavior would be, I click on the conversation and I write my message directly.
>Currently I click on the conversation and I have to click on the text box to write a message.

Created this pull request with code to focus on textarea and prevent double submission - https://github.com/jez500/Private-Message-Messenger/pull/24. Let me know if you tried it.

**Comment by jez500** [comment]
A `selected` class is now added to the current open thread, this must have been something that I intended to do as the css was there just not the js adding the functionality.

Anyway you can remove any custom js but you might need to change you css to use `.selected` rather than `.active`
