### ISSUE TITLE
undefined variable first_thread in JsonEndpoint

### ISSUE THREAD

**Issue by olivier-br** [jez500/Private-Message-Messenger#25]
Here is the error : 

> Notice: Undefined variable: first_thread in Drupal\private_message_messenger\Controller\JsonEndpoint->buildThreadCollection() (line 206

Maybe due to the php version i use
I changed line 206 in JsonEndpoint.php to get rid of it.

```
- if (!$first_thread || $processed_thread['threadId'] != $first_thread['threadId']) {
+ if (!isset($first_thread) || $processed_thread['threadId'] != $first_thread['threadId']) {
```

**Comment by jez500** [comment]
Thanks for reporting this, I couldn't replicate but I added something that should fix it https://github.com/jez500/Private-Message-Messenger/blob/master/src/Controller/JsonEndpoint.php#L210
