### ISSUE TITLE
Number does not disappear on notification block despite reading messages

### ISSUE THREAD

**Issue by UmitAltun** [jez500/Private-Message-Messenger#31]
First of all thank you for this wonderful modul. I installed it in my system, it works great. But there is a problem with the notification. You read the messages and the notification disappears. It appears again when you refresh the page. What is the reason of this. How can I fix?

**Comment by LubomirKurpel** [comment]
This looks like a problem with twig caching. But I have no idea how to fix this at the moment. Going to dip deeper since I need the same feature.

**Comment by UmitAltun** [comment]
I have solved the problem for now with this module.

https://www.drupal.org/project/blocache
