### ISSUE TITLE
The picture of the thread does not match the selected format

### ISSUE THREAD

**Issue by ZenImagine** [jez500/Private-Message-Messenger#5]
![capture du 2018-02-26 23-46-43](https://user-images.githubusercontent.com/29839861/36700256-72370e08-1b4f-11e8-9332-0f2b8d086d10.png)

In the module configuration, I selected a 50x50 image format

In the thread, the images are not displayed correctly. The style sheet of the module cuts to a width of 30px

![capture du 2018-02-26 23-52-51](https://user-images.githubusercontent.com/29839861/36700514-363a8f0a-1b50-11e8-86dc-2e6385a5a4bd.png)

If I change to 50px the messages are below

**Comment by jez500** [comment]
Your image style likely needs to be `scale and crop` not just `scale`
